export { default as HomeScreen } from './HomeTab'
export { default as AboutScreen } from './AboutTab'
export { default as ResumeScreen } from './ResumeTab'
export { default as PortfolioScreen } from './PortfolioTab'
export { default as BlogScreen } from './BlogTab'
